### PR TITLE
Fix error when writing the log and stdin

### PR DESCRIPTION
**Pull request by JorMaister**

### CODE REVIEW

**Review by pconesa — APPROVED** [review]

**Comment by delarosatrevin** [comment]
@JorMaister @pconesa Do you know if e2ih.py, a script that we execute as Eman2 process, might be suffering from the same issue? I got some "Line too long" kind of error in test_convert test, but I didn't have time to check it.

**Comment by JorMaister** [comment]
Hi @delarosatrevin, 
Do you mean the scipion-em-eman tests? All of them pass for me. If you are referring to another test, can you please tell what test is, so I can try to reproduce the issue mentioned?

**Comment by delarosatrevin** [comment]
It is not in eman plugin, but it depends on Eman2 binary, since it is used internally in ImageHandler for some format that xmippLib is not able to handle. 

The test is the following:
scipion tests pwem.tests.data.test_data.TestImageHandler

```
(env) josem@artemis:~/work/development/scipion3/source/plugins$ scipion tests pwem.tests.data.test_data.TestImageHandler

Scipion v3.0 () devel

>>>>> python  /home/josem/work/development/scipion3/source/scipion-pyworkflow/pyworkflow/apps/pw_run_tests.py "pwem.tests.data.test_data.TestImageHandler"
Running tests....
[ RUN   OK ] TestImageHandler.testExistLocation (0.000 secs)
Converting: 
/home/josem/work/development/scipion3/data/tests/xmipp_tutorial/micrographs/BPV_1386.mrc -> /tmp/BPV_1386.img
** Running: ' /home/josem/work/development/scipion3/source/plugins/scipion-em-eman2/eman2/e2ih.py /home/josem/work/development/scipion3/data/tests/xmipp_tutorial/micrographs/BPV_1386.mrc /tmp/BPV_1386.img'
/home/josem/work/development/scipion3/source/plugins/scipion-em-eman2/eman2/e2ih.py: 32: /home/josem/work/development/scipion3/source/plugins/scipion-em-eman2/eman2/e2ih.py: 
This script should be launched using the EMAN2 python interpreter 
and its own environment.
This scripts will be used from ImageHandler to manipulate image
format that Xmipp does not support right now.
This way should be deprecated when we read more formats.
: File name too long

```

**Comment by pconesa** [comment]
We'll check.

**Pull request merged**
